"""draft_check_claim"""
import sqlalchemy as sa
from alembic import op

revision = '3a5298410c51'
down_revision = '4f08f3bb9956'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('checking_version', sa.Integer(), nullable=True))
    op.add_column('drafts', sa.Column('check_owner', sa.String(length=36), nullable=True))
    op.add_column('drafts', sa.Column('check_lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'drafts', ['session_id', 'run_id'])
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drafts', type_='unique')
    op.drop_column('drafts', 'check_lease_expires_at')
    op.drop_column('drafts', 'check_owner')
    op.drop_column('drafts', 'checking_version')
    # ### end Alembic commands ###
