"""provider_attempt_receipts"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '4f08f3bb9956'
down_revision = 'dca1208457d7'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('live_session_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_attempts_run_id'), 'provider_attempts', ['run_id'], unique=False)
    op.create_index(op.f('ix_provider_attempts_session_id'), 'provider_attempts', ['session_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_attempts_session_id'), table_name='provider_attempts')
    op.drop_index(op.f('ix_provider_attempts_run_id'), table_name='provider_attempts')
    op.drop_table('provider_attempts')
    # ### end Alembic commands ###
