"""foundation"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '74e84d1a364d'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('browser_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('corpus_indexes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('corpus_checksum', sa.String(length=64), nullable=False),
    sa.Column('bundle', sa.LargeBinary(), nullable=False),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('active_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['corpus_indexes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('context_version', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(length=30), nullable=True),
    sa.Column('as_of', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('index_id', sa.String(length=64), nullable=False),
    sa.Column('context_version', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_session_id', sa.String(length=150), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sdp', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['corpus_indexes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_session_id'),
    sa.UniqueConstraint('session_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_live_sessions_session_id'), 'live_sessions', ['session_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('index_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('context_version', sa.Integer(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fence', sa.Integer(), nullable=False),
    sa.Column('attempt_started', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['corpus_indexes.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_runs_conversation_id'), 'runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_runs_session_id'), 'runs', ['session_id'], unique=False)
    op.create_index('one_active_run_per_conversation', 'runs', ['conversation_id'], unique=True, postgresql_where=sa.text("status IN ('queued','running')"))
    op.create_table('drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('index_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('check', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['corpus_indexes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['browser_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_session_id'), 'drafts', ['session_id'], unique=False)
    op.create_table('live_delegations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('live_session_id', sa.String(length=36), nullable=False),
    sa.Column('delegation_id', sa.String(length=200), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_session_id', 'delegation_id')
    )
    op.create_table('live_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('live_session_id', sa.String(length=36), nullable=False),
    sa.Column('provider_event_id', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_session_id', 'provider_event_id')
    )
    op.create_table('run_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_index(op.f('ix_run_events_run_id'), 'run_events', ['run_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_events_run_id'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_table('live_events')
    op.drop_table('live_delegations')
    op.drop_index(op.f('ix_drafts_session_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index('one_active_run_per_conversation', table_name='runs', postgresql_where=sa.text("status IN ('queued','running')"))
    op.drop_index(op.f('ix_runs_session_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_conversation_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_live_sessions_session_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('active_index')
    op.drop_table('corpus_indexes')
    op.drop_table('browser_sessions')
    # ### end Alembic commands ###
