"""live_event_provenance"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = 'dca1208457d7'
down_revision = '74e84d1a364d'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_delegations', sa.Column('revision', sa.Integer(), nullable=False))
    op.add_column('live_delegations', sa.Column('run_history', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('live_events', sa.Column('kind', sa.String(length=80), nullable=False))
    op.add_column('live_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_events', 'payload')
    op.drop_column('live_events', 'kind')
    op.drop_column('live_delegations', 'run_history')
    op.drop_column('live_delegations', 'revision')
    # ### end Alembic commands ###
